# Generated by Django 5.2.17 on 2026-09-14 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import chat.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("default_model", models.CharField(blank=True, default="", max_length=200)),
                ("base_url", models.CharField(blank=True, default="", max_length=500)),
                ("timeout_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("max_retries", models.PositiveIntegerField(blank=True, null=True)),
                ("keychain_ref", models.CharField(blank=True, default="", max_length=200)),
                ("key_origin", models.CharField(blank=True, default="", max_length=20)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=chat.models.new_uuid, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("archived", models.BooleanField(default=False)),
                ("preferred_model", models.CharField(blank=True, default="", max_length=200)),
                ("system_prompt", models.TextField(blank=True, default="")),
                ("max_output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("input_budget", models.PositiveIntegerField(blank=True, null=True)),
                ("strict_mode", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GenerationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=chat.models.new_uuid, editable=False, unique=True),
                ),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("idempotency_key", models.CharField(max_length=100)),
                ("content_hash", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("preparing", "preparing"),
                            ("streaming", "streaming"),
                            ("done", "done"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                            ("interrupted", "interrupted"),
                            ("abandoned", "abandoned"),
                        ],
                        default="preparing",
                        max_length=12,
                    ),
                ),
                ("snapshot", models.JSONField(default=dict)),
                ("context_used", models.JSONField(default=list)),
                ("requested_model", models.CharField(default="", max_length=200)),
                ("actual_model", models.CharField(blank=True, max_length=200, null=True)),
                ("request_id", models.CharField(blank=True, max_length=200, null=True)),
                ("response_id", models.CharField(blank=True, max_length=200, null=True)),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("stop_reason", models.CharField(blank=True, max_length=50, null=True)),
                ("truncated", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                ("error_message", models.CharField(blank=True, max_length=500, null=True)),
                ("worker_pid", models.IntegerField(blank=True, null=True)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("last_heartbeat", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="active_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chat.generationrun",
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=chat.models.new_uuid, editable=False, unique=True),
                ),
                ("seq", models.PositiveIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "user"), ("assistant", "assistant")], max_length=10
                    ),
                ),
                ("text", models.TextField(default="")),
                ("blocks", models.JSONField(default=list)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ok", "ok"),
                            ("partial", "partial"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                        ],
                        default="ok",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["seq"],
            },
        ),
        migrations.AddField(
            model_name="generationrun",
            name="assistant_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs_as_answer",
                to="chat.message",
            ),
        ),
        migrations.AddField(
            model_name="generationrun",
            name="user_message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs_as_prompt",
                to="chat.message",
            ),
        ),
        migrations.CreateModel(
            name="ModelCatalogCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("profile", models.CharField(max_length=200)),
                ("endpoint", models.CharField(max_length=500)),
                ("payload", models.JSONField(default=list)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("profile",), name="unique_catalog_profile")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["owner", "-updated_at"], name="chat_conver_owner_i_77b144_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["owner", "archived"], name="chat_conver_owner_i_c110d1_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "seq"], name="chat_messag_convers_c897c6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=("conversation", "seq"), name="unique_seq_per_conversation"
            ),
        ),
        migrations.AddIndex(
            model_name="generationrun",
            index=models.Index(
                fields=["conversation", "-started_at"], name="chat_genera_convers_8dab6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generationrun",
            index=models.Index(fields=["state"], name="chat_genera_state_c1c02d_idx"),
        ),
        migrations.AddConstraint(
            model_name="generationrun",
            constraint=models.UniqueConstraint(
                fields=("conversation", "idempotency_key"), name="unique_idem_per_conversation"
            ),
        ),
    ]
