# Generated by Django 5.2.17 on 2026-09-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_temperature_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='response_mode',
            field=models.CharField(choices=[('streaming', 'Streaming'), ('complete', 'Completa')], default='streaming', max_length=10),
        ),
    ]
