# Generated by Django 5.2.17 on 2026-09-15 12:25

import chat.models_tools
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_response_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=chat.models_tools.new_public_id, editable=False, unique=True)),
                ('alias', models.CharField(max_length=60)),
                ('transport', models.CharField(choices=[('stdio', 'stdio'), ('streamable_http', 'streamable_http')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('credential_ref', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(default='disabled', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('last_protocol_version', models.CharField(blank=True, default='', max_length=40)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500, null=True)),
                ('granted_user_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.CharField(max_length=36)),
                ('step', models.PositiveIntegerField()),
                ('model', models.CharField(default='', max_length=200)),
                ('stop_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('tool_use_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['step'],
                'constraints': [models.UniqueConstraint(fields=('run_uuid', 'step'), name='unique_step_per_run')],
            },
        ),
        migrations.CreateModel(
            name='StudyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=chat.models_tools.new_public_id, editable=False, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField(max_length=4000)),
                ('operation_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_notes', to='chat.conversation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=chat.models_tools.new_public_id, editable=False, unique=True)),
                ('run_uuid', models.CharField(max_length=36)),
                ('tool_use_id', models.CharField(max_length=100)),
                ('anthropic_name', models.CharField(max_length=64)),
                ('tool_version', models.CharField(default='', max_length=40)),
                ('connection_revision', models.PositiveIntegerField(default=0)),
                ('args_digest', models.CharField(max_length=64)),
                ('args_preview', models.CharField(default='', max_length=500)),
                ('decision', models.CharField(choices=[('pending', 'pending'), ('approve', 'approve'), ('deny', 'deny')], default='pending', max_length=10)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_approvals', to='chat.conversation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_approvals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToolCatalogSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=200)),
                ('anthropic_name', models.CharField(max_length=64)),
                ('description', models.CharField(default='', max_length=2000)),
                ('input_schema', models.JSONField(default=dict)),
                ('schema_hash', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='chat.mcpconnection')),
            ],
        ),
        migrations.CreateModel(
            name='ToolInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=chat.models_tools.new_public_id, editable=False, unique=True)),
                ('run_uuid', models.CharField(max_length=36)),
                ('step', models.PositiveIntegerField(default=0)),
                ('tool_use_id', models.CharField(max_length=100)),
                ('anthropic_name', models.CharField(max_length=64)),
                ('args', models.JSONField(default=dict)),
                ('decision', models.CharField(default='requested', max_length=20)),
                ('state', models.CharField(choices=[('requested', 'requested'), ('awaiting_approval', 'awaiting_approval'), ('approved', 'approved'), ('running', 'running'), ('done', 'done'), ('failed', 'failed'), ('refused', 'refused'), ('unknown', 'unknown')], default='requested', max_length=20)),
                ('effect', models.CharField(choices=[('none', 'none'), ('done', 'done'), ('unknown', 'unknown')], default='none', max_length=10)),
                ('result_ok', models.BooleanField(null=True)),
                ('result_text', models.TextField(default='', max_length=40000)),
                ('operation_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_invocations', to='chat.conversation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_invocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['step', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='mcpconnection',
            constraint=models.UniqueConstraint(fields=('owner', 'alias'), name='unique_alias_per_owner'),
        ),
        migrations.AddIndex(
            model_name='studynote',
            index=models.Index(fields=['owner', 'conversation', '-created_at'], name='chat_studyn_owner_i_afdb4f_idx'),
        ),
        migrations.AddIndex(
            model_name='toolapproval',
            index=models.Index(fields=['public_id'], name='chat_toolap_public__aaff17_idx'),
        ),
        migrations.AddIndex(
            model_name='toolapproval',
            index=models.Index(fields=['owner', 'conversation'], name='chat_toolap_owner_i_3d8879_idx'),
        ),
        migrations.AddConstraint(
            model_name='toolcatalogsnapshot',
            constraint=models.UniqueConstraint(fields=('connection', 'original_name', 'revision'), name='unique_snapshot_per_revision'),
        ),
        migrations.AddIndex(
            model_name='toolinvocation',
            index=models.Index(fields=['owner', 'conversation', 'run_uuid'], name='chat_toolin_owner_i_fa315b_idx'),
        ),
        migrations.AddConstraint(
            model_name='toolinvocation',
            constraint=models.UniqueConstraint(fields=('conversation', 'run_uuid', 'tool_use_id'), name='unique_tool_use_per_run'),
        ),
    ]
