# Generated by Django 5.2.17 on 2026-09-15 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_mcpconnection_modelstep_studynote_toolapproval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationToolPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tool_prefs', to='chat.conversation')),
            ],
            options={
                'indexes': [models.Index(fields=['conversation'], name='chat_conver_convers_93ba61_idx')],
            },
        ),
    ]
