# Generated by Django 5.2.17 on 2026-09-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_m5_tool_prefs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationrun',
            name='state',
            field=models.CharField(choices=[('preparing', 'preparing'), ('streaming', 'streaming'), ('awaiting_approval', 'awaiting_approval'), ('done', 'done'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('interrupted', 'interrupted'), ('abandoned', 'abandoned')], default='preparing', max_length=20),
        ),
    ]
