# Generated by Django 5.2.17 on 2026-09-15 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_m5_run_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('upload', 'upload'), ('processing', 'processing'), ('ready', 'ready'), ('partial', 'partial'), ('needs_ocr', 'needs_ocr'), ('failed', 'failed')], default='upload', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_docs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.PositiveIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveIntegerField()),
                ('rel_path', models.CharField(max_length=500)),
                ('extractor', models.CharField(default='', max_length=120)),
                ('text', models.TextField(default='')),
                ('locators', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('is_staging', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='chat.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.documentversion'),
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('state', models.CharField(choices=[('queued', 'queued'), ('extracting', 'extracting'), ('chunking', 'chunking'), ('embedding', 'embedding'), ('publishing', 'publishing'), ('ready', 'ready'), ('cancelled', 'cancelled'), ('failed', 'failed'), ('needs_ocr', 'needs_ocr')], default='queued', max_length=12)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('claimed_by', models.CharField(default='', max_length=120)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('checkpoint', models.JSONField(default=dict)),
                ('error', models.CharField(default='', max_length=500)),
                ('progress_known', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='chat.document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_jobs', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='chat.documentversion')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('active_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_bases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='chat.knowledgebase'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'number'), name='rag_doc_version_unique'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['state', 'lease_until'], name='chat_ingest_state_844129_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='rag_base_owner_name_unique'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['base', 'state'], name='chat_docume_base_id_12851b_idx'),
        ),
    ]
