# Generated by Django 5.2.17 on 2026-09-15 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_document_documentversion_document_active_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('context_hint', models.CharField(default='', max_length=500)),
                ('search_text', models.TextField()),
                ('locator', models.JSONField(default=dict)),
                ('token_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chat.documentversion')),
            ],
        ),
        migrations.CreateModel(
            name='EmbeddingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=200)),
                ('revision', models.CharField(max_length=64)),
                ('dim', models.PositiveIntegerField()),
                ('pipeline_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('model_id', 'revision', 'pipeline_version'), name='rag_profile_unique')],
            },
        ),
        migrations.CreateModel(
            name='ChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField()),
                ('dim', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='chat.chunk')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embeddings', to='chat.embeddingprofile')),
            ],
        ),
        migrations.AddField(
            model_name='chunk',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chunks', to='chat.embeddingprofile'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='active_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.embeddingprofile'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['version', 'profile', 'order'], name='chat_chunk_version_89629b_idx'),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('version', 'profile', 'order'), name='rag_chunk_unique'),
        ),
    ]
