# Generated by Django 5.2.17 on 2026-09-15 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chunk_embeddingprofile_chunkembedding_chunk_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('query', models.CharField(max_length=2000)),
                ('effective_query', models.CharField(max_length=2000)),
                ('bases', models.JSONField(default=list)),
                ('versions', models.JSONField(default=dict)),
                ('method', models.CharField(default='hybrid', max_length=12)),
                ('diagnosis', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_runs', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.embeddingprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('rrf_score', models.FloatField()),
                ('rank_lexical', models.IntegerField(blank=True, null=True)),
                ('rank_vector', models.IntegerField(blank=True, null=True)),
                ('kb_id', models.CharField(max_length=300)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chat.chunk')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='chat.retrievalrun')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
