# Generated by Django 5.2.17 on 2026-09-15 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_retrievalrun_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kb_id', models.CharField(max_length=300)),
                ('source_index', models.PositiveIntegerField()),
                ('locator_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chat.chunk')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='chat.retrievalrun')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bases', models.JSONField(default=list)),
                ('mode', models.CharField(choices=[('always', 'always'), ('tools', 'tools')], default='always', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='chat.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_uuid', models.CharField(max_length=36)),
                ('version_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chat.chunk')),
                ('citation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='chat.citation')),
            ],
        ),
    ]
