# Generated by Django 5.2.17 on 2026-09-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_citation_conversationknowledge_sourcedependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrievalrun',
            name='generation_run_uuid',
            field=models.CharField(db_index=True, default='', max_length=36),
        ),
    ]
