# Generated by Django 5.2.17 on 2026-09-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_retrievalrun_generation_run_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='chunk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.chunk'),
        ),
        migrations.AlterField(
            model_name='sourcedependency',
            name='chunk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.chunk'),
        ),
    ]
