# Generated by Django 5.2.17 on 2026-09-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_citation_chunk_alter_sourcedependency_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionjob',
            name='client_key',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
    ]
