# Generated by Django 5.2.17 on 2026-09-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_ingestionjob_client_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='thinking_budget',
            field=models.PositiveIntegerField(default=1024),
        ),
        migrations.AddField(
            model_name='conversation',
            name='thinking_level',
            field=models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='thinking_mode',
            field=models.CharField(choices=[('default', 'Padrão do modelo'), ('disabled', 'Desativado'), ('enabled', 'Ativado')], default='default', max_length=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='thinking_show_summary',
            field=models.BooleanField(default=False),
        ),
    ]
