# Generated by Django 5.2.17 on 2026-09-15 19:25

import chat.models_agents
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_conversation_thinking_budget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=chat.models_agents.new_public_id, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(default='general', help_text='general | researcher | reviewer | coordinator (rótulo inicial).', max_length=20)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=chat.models_agents.new_public_id, editable=False, unique=True)),
                ('revision', models.PositiveIntegerField()),
                ('task_instructions', models.TextField(blank=True, default='')),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('allowed_tools', models.JSONField(default=list)),
                ('allowed_kb_ids', models.JSONField(default=list)),
                ('delegatable_ids', models.JSONField(default=list)),
                ('thinking_mode', models.CharField(default='default', max_length=10)),
                ('thinking_level', models.CharField(default='medium', max_length=10)),
                ('thinking_budget', models.PositiveIntegerField(default=1024)),
                ('variation_level', models.CharField(default='medium', max_length=10)),
                ('cache_mode', models.CharField(default='stable', max_length=20)),
                ('cache_ttl', models.CharField(default='5m', max_length=5)),
                ('max_child_runs', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='chat.agentdefinition')),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=chat.models_agents.new_public_id, editable=False, unique=True)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('task', models.TextField(blank=True, default='')),
                ('completion_criteria', models.TextField(blank=True, default='')),
                ('state', models.CharField(default='created', max_length=20)),
                ('result_summary', models.TextField(blank=True, default='')),
                ('result_evidence', models.JSONField(default=list)),
                ('limitations', models.TextField(blank=True, default='')),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(default=dict)),
                ('checkpoint', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='chat.conversation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='chat.agentrun')),
                ('agent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.agentversion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=chat.models_agents.new_public_id, editable=False, unique=True)),
                ('kind', models.CharField(help_text='reserve_output | usage | cache_write | cache_read | child_slot | call_slot', max_length=20)),
                ('tokens', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('root_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_lines', to='chat.agentrun')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_ledger_lines', to='chat.agentrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CacheObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=chat.models_agents.new_public_id, editable=False, unique=True)),
                ('step', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(default='disabled', max_length=20)),
                ('ttl', models.CharField(default='5m', max_length=5)),
                ('eligible', models.BooleanField(default=False)),
                ('diagnosis', models.CharField(blank=True, default='', max_length=300)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_creation_input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_read_input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cache_observations', to='chat.agentrun')),
            ],
            options={
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=chat.models_agents.new_public_id, editable=False, unique=True)),
                ('tool_use_id', models.CharField(default='', max_length=200)),
                ('released_context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delegation', to='chat.agentrun')),
                ('parent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='chat.agentrun')),
            ],
        ),
        migrations.CreateModel(
            name='RunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=chat.models_agents.new_public_id, editable=False, unique=True)),
                ('seq', models.PositiveIntegerField()),
                ('kind', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chat.agentrun')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.AddConstraint(
            model_name='agentdefinition',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_agent_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='agentversion',
            constraint=models.UniqueConstraint(fields=('definition', 'revision'), name='unique_agent_revision'),
        ),
        migrations.AddConstraint(
            model_name='runevent',
            constraint=models.UniqueConstraint(fields=('run', 'seq'), name='unique_event_seq_per_run'),
        ),
    ]
