# Generated by Django 5.2.17 on 2026-09-15 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_agentdefinition_agentversion_agentrun_budgetledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='agent_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='chat.agentdefinition'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='agent_mode',
            field=models.CharField(choices=[('chat', 'Chat'), ('agent', 'Agente'), ('team', 'Equipe')], default='chat', max_length=10),
        ),
    ]
