# Generated by Django 5.2.17 on 2026-09-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_conversation_agent_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='cache_mode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='cache_ttl',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='modelstep',
            name='cache_creation_detail',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='modelstep',
            name='cache_creation_input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelstep',
            name='cache_read_input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
