# Generated by Django 5.2.17 on 2026-09-16 12:11

import chat.models_runtime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_conversation_cache_mode_conversation_cache_ttl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrun',
            name='claimed_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='generationrun',
            name='state',
            field=models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('preparing', 'preparing'), ('streaming', 'streaming'), ('awaiting_approval', 'awaiting_approval'), ('done', 'done'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('interrupted', 'interrupted'), ('abandoned', 'abandoned')], default='preparing', max_length=20),
        ),
        migrations.CreateModel(
            name='RunJournalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=chat.models_runtime.new_uuid, editable=False, unique=True)),
                ('seq', models.PositiveIntegerField()),
                ('kind', models.CharField(max_length=60)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='chat.generationrun')),
            ],
            options={
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['run', 'seq'], name='chat_runjou_run_id_dc1dea_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'seq'), name='unique_seq_per_run')],
            },
        ),
    ]
