# Generated by Django 5.2.17 on 2026-09-16 12:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_generationrun_claimed_by_alter_generationrun_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('topic', models.CharField(max_length=40)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('state', models.CharField(db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('claimed_by', models.CharField(default='', max_length=120)),
                ('error', models.CharField(default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'updated_at'], name='chat_outbox_state_a4cc5b_idx')],
            },
        ),
    ]
