apiVersion: v1
kind: Service
metadata:
  name: chat-local-web
  namespace: chat-local
spec:
  selector:
    app.kubernetes.io/name: claude-chat-local
  ports:
    - name: http
      port: 80
      targetPort: http
